### PR TITLE
Feature/multiple acl operations

### LINKED ISSUE #70: Add support for `--producer` and `--consumer` ACL actions
## Expected Behavior
I'm not an expert on [Kafka ACLs](https://docs.confluent.io/current/kafka/authorization.html#using-acls), but it seems that the Kafka commands have shortcuts for adding Principals as either a Producer or Consumer.

```
bin/kafka-acls --bootstrap-server localhost:9092 --command-config adminclient-configs.conf \
 --add --allow-principal User:janedoe@bigdata.com \
 --producer --topic test-topic
```
```
bin/kafka-acls --bootstrap-server localhost:9092 --command-config adminclient-configs.conf \
 --add --allow-principal User:janedoe@bigdata.com \
 --consumer --topic test-topic --group Group-1
```

It looks like the `--producer` option will add Create, Read, Write, and Describe, while `--consumer` will add Read and Describe?

## Actual Behavior
I think the current behavior of `kafka_lib` is that only a single `acl_operation` can be added at a time, meaning that multiple tasks would be required to add sufficient permissions for many use-cases (?)

Allowing a single task to specify multiple `acl_operation` would also be an improvement?

## Specifications

  - Library version: 0.10.0
  - Result of `pip list` command: 
  - Kafka version:
  - Python version:
  - OS:

### LINKED ISSUE #124: Unnecessary requirement for acl_operation in module kafka_acls
## Expected Behavior

Delete all ACLs for a specific Topic

## Actual Behavior

acl_operation is a required attributes for kafka_acls module which prevent to delete all ACLs for a specific Topic

## Play to Reproduce the Problem

```yaml
- name: Delete all ACLs for a Topic in Kafka
  StephenSorriaux.ansible_kafka_admin.kafka_acl.kafka_acls:
    bootstrap_servers: "{{ lookup('ENV', 'KAFKA_BOOTSTRAP_SERVERS') }}"
    acls:
      - acl_resource_type: 'topic'
        name: 'test'
        state: 'absent'
```

## Logs from the play with Ansible in debug mode

```acl_operation is required```

This error is explicitly thrown here but in general not declared as an required attribute. I think its an unnecessary line of code.

https://github.com/StephenSorriaux/ansible-kafka-admin/blob/547ff8c38b7383bdc3f4fafb1d303d28d1c484ae/module_utils/kafka_lib_acl.py#L57

Kafka has not that requirement.

## Specifications

  - Library version: 0.15.1
  - Result of `pip list` command: 
  - Kafka version: 2.8.1
  - Python version: 3.8
  - OS:  5.15.12-100.fc34.x86_64

### PR DESCRIPTION
**Pull request by saiello**
Fixes #70 
Fixes #124 

## Proposed Changes

 - Allow to specify multiple acl_operations 

```

 - name: "Create a single ACL with multiple operations"
      kafka_acl:
        name: 'my-topic'
        api_version: "2.6.0"
        acl_resource_type: 'topic'
        acl_principal: 'User:producer-client'
        acl_operations: 
          - 'write'
          - 'describe'
          - 'create'
        acl_permission: 'allow'
        acl_pattern_type: 'literal'
        bootstrap_servers: "localhost:9092"

- name: "Create multiple ACL with multiple operations"
      kafka_acls:

        acls:
          - name: 'my-topic'
            acl_resource_type: 'topic'
            acl_principal: 'User:consumer-client'
            acl_operations: 
              - 'describe'
              - 'read'
            acl_permission: 'allow'
            acl_pattern_type: 'literal'

          - name: 'my-consumer-group'
            acl_resource_type: 'group'
            acl_principal: 'User:consumer-client'
            acl_operations: 
              - 'read'
            acl_permission: 'allow'
            acl_pattern_type: 'literal'

        api_version: "2.6.0"
        bootstrap_servers: "localhost:9092"
```

- Allow to use state=absent without acl_operation/acl_operations 

```
    - name: "Delete any ACL of a given resource"
      kafka_acls:

        acls:
          - name: 'my-topic'
            acl_principal: 'User:consumer-client'
            state: 'absent'

        bootstrap_servers: "localhost:9092"
```

### CODE REVIEW

**Comment by ryarnyah** [comment]
We need to look more to this PR but it's seem be to be a great improvement! Thanks!!!!

**Comment by ryarnyah** [comment]
LGMT! Can you add some test with `acl_operations` in https://github.com/StephenSorriaux/ansible-kafka-admin/blob/master/molecule/default/tests/test_acl_default.py to ensure that this won't be breaked in the future?

**Comment by saiello** [comment]
@ryarnyah I mean to rebase on master once the #134 will be merged to use the same testing approach used there.

**Comment by ryarnyah** [comment]
@saiello In this case it might be a better idea to reuse default scenario to reuse existing tests (ACLs is supported from 0.11.0 to X and in your case it's only to ensure that it won't be breaked in the future). Furthermore we are already limited on concurrent github action that can be done so if we add another scenario we will increase drastically build time.

**Comment by saiello** [comment]
> @saiello In this case it might be a better idea to reuse default scenario to reuse existing tests (ACLs is supported from 0.11.0 to X and in your case it's only to ensure that it won't be breaked in the future). Furthermore we are already limited on concurrent github action that can be done so if we add another scenario we will increase drastically build time.

Yes, you are right! I will add further cases to the existing tests! 

I have some idea to optimize the github actions usage. I would like to work on them later. Let me know if you already have some thought about it.

**Comment by saiello** [comment]
@ryarnyah tests added

**Comment by ryarnyah** [comment]
@saiello thank you!

**Pull request merged**
