### PR TITLE
Put SCRAM methods under try/except in kafka_protocol.py

### PR DESCRIPTION
**Pull request by arenard**
Looks like an indentation error when SCRAM methods where added to kafka_protocol.py

### CODE REVIEW

**Comment by StephenSorriaux** [comment]
Hello,

Thank you for the PR.

Is this supposed to fix any issue? As far as I can tell, and as the comment is suggesting, the `try/except` logic is there to implement some Kafka protocol requests/responses that would be available in the `kafka-python` lib when a release is cut. In the meantime (which has been 3years+, but with the latest changes on the `kafka-python` project, there is still hope), and to avoid asking our users to pin the `kafka-python` lib version to a git commit, we decided to get it back in this project.
On the other hand, the `DescribeUserScramCredentialsResponse_v0` and others implementations are our own, and not part of the `kafka-python` lib, hence the reason why they are not part of the `try/exept` logic.

**Comment by arenard** [comment]
Hello, 

Yes I see the point and effectively, it seems there is a new hope on kafka-python side. However it seems that the project while revived is still not releasing new versions for now.

Of course it fixes some issues :-). From what I've seen there is curently two problems : 

- First we see errors related to `DescribeUserScramCredentials*v0`  and `AlterUserScramCredentials*v0` in kafka_manager.py when using any kafka-admin modules in ansible 2.13 to 2.16. Schemas inside moved blocks are relying on some custom types definition into `try/except` block logic like `CompactArray`, `CompactString`, `CompactBytes`, `TaggedFields`. 
=> Maybe we could import them from `kafka-python` for code outside of `try/except` block but as we have a custom one into `try/except`, it may be confusing to do both.

- Secondly, we see headers errors on kafka (at least on kraft enabled kafka 3.6.0 clusters) when using kafka_user(s) module to manage SCRAM users. It is related to `FLEXIBLE_VERSION` logic allowing to shift from `RequestHeader` to `RequestHeaderV2` which sits into `try/except` too. Moving `DescribeUserScramCredentials*v0`  and `AlterUserScramCredentials*v0` into `try/except` block solves it too.

**Comment by StephenSorriaux** [comment]
I opened #163 where I removed the logic around using stuff from `kafka-python` if it is there. Can you please try it and let met know whether if fixes your issue or not?

**Comment by StephenSorriaux** [comment]
I merged #163 and will now close this one, please let me know if it does not fix your issue.

**Pull request closed without merging**
